### PR TITLE
Disqus integration for single nodes.

### PR DESCRIPTION
**Pull request by fte378**
Hi,

disqus integration is on your ToDo list - I did it for my blog.

With kind regards,
Frank Tegtmeyer

### CODE REVIEW

**Comment by alanorth** [comment]
Patch applies and seems to work fine (I added a temporary `disqusShortname` in my config and the code loads, albeit disabled because of localhost). Thank you for helping, @fte378. 😄

**Comment by fte378** [comment]
Thank you for the theme!
If you want to see it in action - see photoblog.tegtmeyer.net - there are still some things to solve (I'm just working on cookie_consent integration).

**Comment by alanorth** [comment]
Awesome, another photo-centric blog (like mine!). BTW, if you ever write in German, I added support for Hugo 0.17's multilingual content feature. It's really cool actually, very seamless, and I already added some Bulgarian content!

https://picturingjordan.com/bg/2016/10/sheikh-zayed-mosque-pearl-aqaba/

**Comment by fte378** [comment]
Thanks - I will have a look at how it works. At the moment I have two different blogs, one in English, one in German. Possibly I can't merge them because the german site will have some other functions too - the blog will be a minor thing there.

**Pull request merged**
